### ISSUE TITLE
coveralls report fails to upload

### ISSUE THREAD

**Issue by IanVaughan** [quiqupltd/libelection#2]
From https://travis-ci.org/quiqupltd/libelection/jobs/404987034
```
* (ExCoveralls.ReportUploadError) Failed to upload the report to 'https://coveralls.io' (reason: status_code = 422, body = {"message":"Couldn't find a repository matching this job.","error":true}).
    (excoveralls) lib/excoveralls/poster.ex:20: ExCoveralls.Poster.execute/2
    (mix) lib/mix/tasks/test.ex:245: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (excoveralls) lib/mix/tasks.ex:51: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
The command "MIX_ENV=test mix do deps.get, test && mix credo && mix coveralls.travis" exited with 1.
```

Also fails locally via `mix coveralls.travis`

**Comment by zorbash** [comment]
This is because someone changed the org name from `QuiqUpLTD` to `quiqupltd` (👏  for the change btw).

**Comment by zorbash** [comment]
I synced the repo info on coveralls, so I think this should not fail anymore.

**Comment by IanVaughan** [comment]
Looks good, works now, thanks!
