### ISSUE TITLE
Getting a crash since I updated the node pool

### ISSUE THREAD

**Issue by danhawkins** [quiqupltd/libelection#9]
It seems that libelection is expecting a resourceVersion, but it's not there

Kubernetes Version 1.23.16-gke.1400

```bash
realtimeex-6c5c69b4bf-xs6pz realtimeex 09:56:36.744 [error] GenServer Election.Elector terminating
realtimeex-6c5c69b4bf-xs6pz realtimeex ** (FunctionClauseError) no function clause matching in anonymous fn/1 in Election.Strategy.Kubernetes.parse_response/2
realtimeex-6c5c69b4bf-xs6pz realtimeex     (libelection) lib/strategy/kubernetes.ex:77: anonymous fn(%{"ip" => "10.8.2.137", "nodeName" => "gke-dev-e2-spot-pool-6b613fad-jwf2", "targetRef" => %{"kind" => "Pod", "name" => "realtimeex-6c5c69b4bf-xs6pz", "namespace" => "staging", "uid" => "86d8ea88-8e9f-4873-b1c0-2dd6c25d4a6e"}}) in Election.Strategy.Kubernetes.parse_response/2
realtimeex-6c5c69b4bf-xs6pz realtimeex     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
realtimeex-6c5c69b4bf-xs6pz realtimeex     (elixir) lib/enum.ex:2986: Enum.flat_map_list/2
realtimeex-6c5c69b4bf-xs6pz realtimeex     (libelection) lib/strategy/kubernetes.ex:74: anonymous fn/3 in Election.Strategy.Kubernetes.parse_response/2
realtimeex-6c5c69b4bf-xs6pz realtimeex     (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
realtimeex-6c5c69b4bf-xs6pz realtimeex     (libelection) lib/strategy/kubernetes.ex:23: Election.Strategy.Kubernetes.leader/2
realtimeex-6c5c69b4bf-xs6pz realtimeex     (libelection) lib/elector.ex:102: Election.Elector.determine_election/2
realtimeex-6c5c69b4bf-xs6pz realtimeex     (libelection) lib/elector.ex:66: Election.Elector.handle_cast/2
realtimeex-6c5c69b4bf-xs6pz realtimeex Last message: :timeout
```

**Comment by zorbash** [comment]
That's odd. According to the API docs for [v1.23](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#objectreference-v1-core) the `targetRef` which is an [ObjectReference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#objectreference-v1-core) should contain a `resourceVersion` and it doesn't optional (see: [type](https://github.com/kubernetes/kubernetes/blob/v1.23.16/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L187))

**Comment by danhawkins** [comment]
@zorbash it has +optional, doesn't that mean it is optional?
